services:
  node:
    tty: true
    build:
      dockerfile: Dockerfile.dev
    environment:
      SESSION_SECRET: "asdf"
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:pass123@db:5432/dfunkt
      LOGIN_KEY: 1234567890abcdef
      HIVE_URL: http://nyckeln:7004/api/v1
      HIVE_API_KEY: aaaa
      SSO_API_URL: http://nyckeln:7003
      OIDC_PROVIDER: http://localhost:7003
      OIDC_ID: client-id
      OIDC_SECRET: client-secret
      REDIRECT_URL: http://localhost:5000/login/callback
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: dfunkt

    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
      
  nyckeln:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    configs:
      - source: nyckeln.yaml
        target: /config.yaml
    ports:
      - 7003:7003
      - 7004:7004

configs:
  nginx.conf:
    content: |
      events {}

      http {
        server {
          listen 7003;

          location / {
            proxy_pass http://nyckeln:7003;
          }
        }
      }

  nyckeln.yaml:
    content: |
      clients:
        - id: client-id
          secret: client-secret
          redirect_uris:
            - http://localhost:5000/login/callback

      users:
        - ug_kth_id: some-id
          kth_id: turetek
          email: turetek@kth.se
          first_name: Ture
          family_name: Teknolog
          picture: https://thskth.se/wp-content/uploads/2023/06/ths-logo-bla-01-300x294-1.png
          thumbnail: https://thskth.se/wp-content/uploads/2019/12/ths-logo-svart-01.png
        - ug_kth_id: some-other-id
          kth_id: diadat
          email: diadat@kth.se
          first_name: Diana
          family_name: Datalog
          year_tag: D-83
        - ug_kth_id: yet-anouther-id
          kth_id: marmed
          email: marmed@kth.se
          first_name: Martin
          family_name: Median
          year_tag: Me-00
        - ug_kth_id: even-more
          kth_id: karklu
          email: karklu@kth.se
          first_name: Karin
          family_name: Klubbare
          year_tag: D-85


      hive:
        groups:
          - name: Systemansvarig
            id: d-sys
            domain: example.com
            members:
              - turetek
            tags:
              - id: mandate
            permissions:
              - id: admin
              - id: search
